README.md
Made minor edits to make the instructions more active and fixed some typos.
=> Edits to readme file

Dockerfile, README.md, bin/setenv.sh, build.sh, docker-entrypoint.sh
I fixed the issue related to JMX and updated the docs a bit.
=> Fixed prsysmgmt issue with connection via JMX and updated docs

Dockerfile, README.md
Fix after tomcat changed there base image and removed the already retrieved public keys for the keys in $GPG_KEYS.
=>  retrieve the public gpg keys from a key server (tested)

Dockerfile
most of the steps in dockerfile can be done in batch operation.  this reduces build time, improves layer caching, and provides better readability.  there is no functionality change in this code change.
=> consolidate repetitive dockerfile steps

Dockerfile, README.md
Incorporated change by @viper0131 and kept tomcat at 7 for now.
=> #14 Changed to jre8

.travis.yml, Makefile, build.sh
=> Add travis build and DockerHub push

scripts/docker-entrypoint.sh, tests/pega-web-ready-testcases.yaml, tests/test-artifacts/prconfig.xml, tests/test-artifacts/prlog4j2.xml
Adding automation for test supporting monunting prconfig and prlog4j2 files
=> Epic 36254

tomcat-conf/context.xml.tmpl
=> Remove Tomcat DataSourceFactory and fall back to DBCP2

Dockerfile, README.md
Exposing NODE_TIER as environment variable as per issue #70
=> ISSUE-70 Expose NODE_TIER as Env Var

Dockerfile, README.md, tests/pega-web-ready-release-testcases.yaml, tests/pega-web-ready-testcases.yaml
changes to run image with non root user.
=> changes for non root pega user

tomcat-conf/Catalina/localhost/prweb.xml
Allow Stream configuration based on env var: PEGA_STREAM_URL. On helm chart side we will not allow this in combination with pega-stream deployment tier.
=> Support Stream service through env var

Dockerfile, README.md
Enabled read write access to web apps folder due to #BUG-528213
=> BUG-528213 enabled readwrite access to webapps folder

tomcat-conf/server.xml
- Added server xml to docker-pega-web-ready
- Added RemoteIpValve, modified access log print pattern to include X-Forwarded-For value to default server.xml
=> US-386308 - Added server.xml with RemoteIpValve to print Source IP

Dockerfile, README.md, tests/pega-web-ready-testcases.yaml, tests/test-artifacts/templates/expected_context.xml
The default value of JDBC_INITIAL_SIZE was changed from 10 to 4. Tests have been updated and run.
=> ISSUE-99: Changed the default initial JDBC size to 4 and updated tests

Dockerfile, tests/pega-web-ready-testcases.yaml
Include jmx-exporter.jar to make it available for emitting metrics in the prometheus format.
=> Include jmx/prometheus lib.

tomcat-conf/server.xml, tomcat-webapps/ROOT/error400.html, tomcat-webapps/ROOT/error403.html, tomcat-webapps/ROOT/error404.html, tomcat-webapps/ROOT/error405.html
US-410526: Improve the UI for 400, 403, 405, and 404 error codes.
PR includes the following changes
1. Html files are added for error code 404, 400, 405 and 403
2. Server.xml is modified to add the configuration to display newly added error files at tomcat level and Pega level errors.
This feature supports backward compatability
=> US-410526 : Added error files and config

README.md
Minor change - validating PR process.
=>  Switch from travis-ci.org to travis-ci.com

Dockerfile
=> US-452345 (Implement Docker HEALTHCHECK for pega images)

scripts/docker-entrypoint.sh
Otherwise it shows like "NODE_TYPE (run) IS NOT SUPPORTED BY THIS IMAGE"
=> Fix error message for DDS and Universal types

Dockerfile, README.md, scripts/docker-entrypoint.sh, tests/pega-web-ready-testcases.yaml, tests/test-artifacts/CUSTOM_ARTIFACTORY_APIKEY, tests/test-artifacts/CUSTOM_ARTIFACTORY_APIKEY_HEADER, tests/test-artifacts/CUSTOM_ARTIFACTORY_PASSWORD, tests/test-artifacts/CUSTOM_ARTIFACTORY_USERNAME, tests/test-artifacts/catalina.sh
Added Support for downloading JDBC driver from an artifactory which is secured with authentication
=> Added Support for downloading JDBC driver from an artifactory which is secured with authentication

tomcat-bin/setenv.sh
Added classloader timeout settings
=> US-492837 (Configurable timeouts to support database failovers)

tests/pega-web-ready-testcases.yaml
https://github.com/GoogleContainerTools/container-structure-test/pull/314 https://github.com/GoogleContainerTools/container-structure-test/pull/315
=> update test based on upstream change

scripts/docker-entrypoint.sh
Reverting script changes to authentication headers out of a sense of caution.
=> Revert script changes authentication headers.

tomcat-bin/setenv.sh
=> Fix pyUnpackBasePath setting.

tomcat-conf/server.xml
=> Remove arbitrary redirect port from connector.

.grype.yaml, Dockerfile
Update jmx exporter library to address GHSA.
=> Address GHSA for snakeyaml 1.33

Dockerfile, scripts/docker-entrypoint.sh, tests/pega-web-ready-testcases.yaml, tests/test-artifacts/krb5.conf, tomcat-bin/setenv.sh
Added support for mounting of krb5.conf file - Decisioning use-case
=> Added support for mounting of krb5.conf file

Dockerfile, README.md, tests/test-artifacts/expected_prweb.xml, tomcat-conf/Catalina/localhost/prweb.xml
US-547544 : Hazelcast enablement prconfig added
=> US-547544 : Hazelcast enablement prconfig added

scripts/docker-entrypoint.sh, tests/pega-web-ready-testcases.yaml, tests/test-artifacts/catalina.properties, tests/test-artifacts/java.security.overwrite, tests/test-artifacts/prbootstrap.properties, tests/test-artifacts/tomcat-web.xml
US-56177 Moving new mounted files to locations
Added support for
catalina.properties
prbootstrap.properties
java.security.overwrite
tomcat-web.xml
=> US-56177 Moving new mounted files to locations

.grype.yaml
add CVE-2024-24791 to the ignore list
=> BUG-878315 add CVE-2024-24791 to the ignore list

tests/pega-web-ready-testcases.yaml, tomcat-bin/setenv.sh
Remove IS_RASP_ENABLED and use RASP_ACTION='DISABLE' to disable RASP. 
By default, RASP is enabled in Pega Platform ‘25 and later.
=> Remove IS_RASP_ENABLED and use RASP_ACTION='DISABLE' to disable RASP. 
