pegasystems/docker-pega-web-ready

- .travis.yml
#34 Per agreement with the Pega security team, the default build-failure threshold for the image scanner in this OSS project should be High, not Medium.
> Set threshold for Clair CVE scanning

- .travis.yml
Travis-CI changed their docker networking so that clair scanner now needs to connect to the DB at an IP from the docker0 device rather than eth0.
> Fix clair-scanner network problem in travis

- scripts/docker-entrypoint.sh
When the user mounts prlog4j2 file in /opt/pega/config folder, the Pega process uses the mounted file.
> Adding support to mount prlog4j2 file

- Dockerfile
- tests/pega-web-ready-testcases.yaml
- tests/test-artifacts/templates/context.xml.tmpl
- tests/test-artifacts/templates/expected_context.xml
- tomcat-conf/context.xml.tmpl
Tomcat 8 updated dbcp to 2.0, which changed a few of the setting names.  Since this image uses Tomcat 9 now, we need to use the updated versions.
> update setting names to dbcp 2 versions

- tomcat-bin/setenv.sh
Pass node tier from Kubernetes into Pega so that settings information can be viewed by tiers.
> Pass node tier to Pega 

- tomcat-bin/setenv.sh
- tomcat-conf/Catalina/localhost/prweb.xml
Introducing the cloud/isNodeAgnosticAdminStudio variable to remove node specific functionality from Admin studio for Kubernetes environments. 
This variable has been created as functionality specific variable instead of a generic variable like isKubernetes. Also this variable is being added to the docker image instead of helm charts as advised by System Management.
> Pass Kubernetes admin studio functional variable

- Dockerfile
- README.md
- tests/pega-web-ready-testcases.yaml
Updating the JDBC connection properties to remove the default value of `socketTimeout=90`. This was causing problems in MSSQL deployments because the timeout of 90ms was too short.
Updating other JDBC configuration default settings as per the recommendation from Pega Cloud service teams and client feedback over the time.
Pega refs BUG-547108, SPACE-15322
_Edited by dcasavant_
> ISSUE-67 Modified JDBC connection props to fix MSSQL read timeout connection exception

- Dockerfile
- tomcat-bin/setenv.sh
This PR is to default the JMX Host name as the pod IP address and the changes should be backward compatible as well since defaulting to pod IP shouldn't restrict the access from the namespace or break any existing functionality. These changes are required to be made to support K8s upgrade-deploy action while the internals are mentioned and already discussed as part of story.
> US-325026 Defaulting JMX host name to use pod IP

- tomcat-conf/Catalina/localhost/prweb.xml
This change will allow testing with types other than the default.
> Allow explicitly setting search deployment type

- Dockerfile
- tomcat-bin/setenv.sh
This set of changes will allow JMX connectivity to be customized or completely disabled.  Customer environments may prefer to restrict JMX access according to the organizational mandates/security standards.  By default the original behavior persists if additional configuration is not provided.
To enable custom JMX connectivity, set the USE_CUSTOM_JMX_CONNECTION=true and provide JMX JVM arguments via the JAVA_OPTS env var.
> Add support for customizing JMX connectivity (or disabling it).

- Dockerfile
- README.md
- scripts/docker-entrypoint.sh
- tests/pega-web-ready-testcases.yaml
- tests/test-artifacts/HZ_CS_AUTH_PASSWORD
- tests/test-artifacts/HZ_CS_AUTH_USERNAME
- tests/test-artifacts/catalina.sh
- tomcat-conf/Catalina/localhost/prweb.xml
Changes to support hz c/s authentication. We take username and password, and create secrets out of this and mount volumes created out of these secrets on container files. Tomcat gets these values through prweb.xml only when hz c/s mode is enabled.
> US-391911-1:changes to support authentication in hz c/s mode in k8s

- tomcat-bin/setenv.sh
For better tunability of JVM Pega recommends defaults for some of the JVM arguments.
Here, these parameters can be set as **CATALINA_OPTS**. Earlier,  **CATALINA_OPTS** environment variable was not exposed to set externally as it is always initialized to an empty string(""). Removed this to expose the CATALANA_OPTS.
Added two sets of JVM arguments:
1. The arguments which are not overridden and are absolute defaults.   
2. The arguments with the flexibility to override by setting the environment variable externally.
> Default overrideable and non-overrideable parameters for JVM tunability

- tomcat-bin/setenv.sh
Currently, SDEA uses jdk8 and the unified GC logging format is supported from jdk9, hence breaking their environments. 
https://openjdk.java.net/jeps/271
Earlier, our assumption was that the consumers of this image use jdk11. 
Removed the flag for the same purpose.
> BUG-622973 : Remove jdk8 unsupported JVM arguments

- tomcat-conf/server.xml
Resolves #101 
This PR flips the `showReport` and `showServerInfo` flags to false on the default `ErrorReportValve` so that the error pages only contain the header with the HTTP status info.
> Don't show version or stacktrace on error pages

- scripts/docker-entrypoint.sh
- tests/pega-web-ready-testcases.yaml
"docker-pega-web-ready" by default does not accept empty db_password.  So, we removed that check here and added test case for the same.  
An issue was raised that the passwords are in plaintext format in context.xml inside the container.  So, we are mitigating this by leveraging aws-secret-manager-jdbc to contact aws and fetch secret value to establish a DB connection.  When going by this method, password is no longer mandatory.
This will be leveraged by pega-cloud.
> Removed empty check for DB_PASSWORD

- scripts/docker-entrypoint.sh
- tests/pega-web-ready-testcases.yaml
- tests/test-artifacts/server.xml
- tests/test-artifacts/web.xml
* Allow overrides of Tomcat's server.xml and prweb's web.xml
* Default to existing files if mounted files do not exist in /opt/pega/config
* Associated with changes to pega-helm-charts: https://github.com/pegasystems/pega-helm-charts/pull/261
> Allow overrides of server.xml and web.xml

- tomcat-bin/setenv.sh
This includes a change(related to GC logs JVM argument) from https://github.com/pegasystems/docker-pega-web-ready/pull/95 which was then reverted in   https://github.com/pegasystems/docker-pega-web-ready/pull/96 because of SDEA being using java8. Now that SDEA has moved to java11 this should not be a problem.
> Added jvm9+ supported GC logs JVM argument

- Dockerfile
- README.md
- tomcat-bin/setenv.sh
The documentation in this repo claims that the pega web container supports the ability to configure the 8080 connector's maxThreads, and indicates that if the client doesn't set the value, the default will be 300.  The image, however, doesn't honor this setting and instead always uses Tomcat's default of 200.  After some investigation, it appears that the [previous way of setting maxThreads](https://github.com/pegasystems/docker-pega-web-ready/blob/65a822bf41bbddf5d30465942ca4e3f146c67681/tomcat-bin/setenv.sh#L33) wasn't having any effect and isn't supported by Tomcat.  Instead, this property should be set on the connector in server.xml.  
Given that server.xml is now supplied by our helm templates and a direct docker run of this container isn't supported, I think it's best to just delete …
> Remove all references to MAX_THREADS

- tests/test-artifacts/templates/expected_server.xml
- tests/test-artifacts/templates/server.xml.tmpl
- tomcat-conf/server.xml
Disabling autoDeploy in tomcat as it is a feature that is not leveraged by pega deployments.
> Disable autoDeploy feature

- .github/workflows/docker-build.yml
v1 of the CodeQL Action was deprecated on January 18th, 2023, and is no longer updated or supported. For better performance, improved security, and new features, upgrade to v2. For more information, see https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
> updated upload-sarif GitHub action from v1 to v2.

- scripts/docker-entrypoint.sh
This checks if file settings archive script exists in file system, if yes, it runs the script. This is specifically for pega cloudk
> Feature/US-572740 - Pod start up change to download file settings archive for pega cloudk

- scripts/docker-entrypoint.sh
This checks if file settings archive script exists in file system, if yes, it runs the script. if there is any error, it fails the pod startup. This is specifically for pega cloudk
Reverting the above changes done in the #201  as this logic should be present in different repository. This pr has a dependency with docker-pega PR. Both PRs should be merged together to have the feature available.
> US-583793-2 - Handling failing of package download

- .github/workflows/github-actions-stale.yml
1: Stale action workflow to handle github repo issues & pull requests with no activity for more than 60 days which are labelled with pending info and it will be marked as stale.
2: Stale issues & PR's will proceed for closing with respective comments, if it doesn't receive any activity with in 7 days after making it as stale .
> US-614190: Stale action workflow to handle for github repo issues & PR's with no activity

- Dockerfile
- docs/Building-Image-With-Own-OS-And-JDK.md
Using detemplatize image as multi stage docker build, to avoid writing custom code to copy detemplatize library for building images with different OS and JDK.
> US-620855 Add detemplatize executable using multi stage docker build

- .github/workflows/github-actions-stale.yml
increase operations-per-run for stale action bot as default 30 exceeding the limit and operations are exiting with (No more operations left! Exiting...)
> BUG-879464: increase operations-per-run for stale action bot as default 30 is not sufficient

- .github/workflows/docker-build.yml
- .grype.yaml
Updated upload-artifact version to v4
The CVE-2024-34156 and CVE-2024-34158 vulnerabilities are being ignored because there are currently no available fixes for them
Created an internal work item(BUG-888445) to fix the above vulnerabilities.
> BUG-888436: Update upload-artifact version to v4

- README.md
From: Peterson, John <John.Peterson@pega.com> 
Sent: Monday, September 23, 2024 2:54 PM
To: Kowalska, Kinga <Kinga.Kowalska@pega.com>; Kumar, Saurabh <Saurabh.Kumar2@in.pega.com>
Cc: Chikkam, Venkata Satya Gopal <VenkataSatyaGopal.Chikkam@in.pega.com>; Saranathan, Raghu <Raghunathan.Saranathan@pega.com>; Talbot, Adam <Adam.Talbot@pega.com>
Subject: RE: Documentation to build custom runtime image.
Hi Kinga,
This looks fine.
Thanks,
John
From: Kowalska, Kinga <Kinga.Kowalska@pega.com> 
Sent: Wednesday, September 18, 2024 7:21 AM
To: Peterson, John <John.Peterson@pega.com>; Kumar, Saurabh <Saurabh.Kumar2@in.pega.com>
Cc: Chikkam, Venkata Satya Gopal <VenkataSatyaGopal.Chikkam@in.pega.com>; Saranathan, Raghu <Raghunathan.Saranathan@pega.com>; Talbot, Adam <Adam.Talbot@pega.com>
Subject: RE: …
> BUG-883938 Move Build custom pega-web-ready doc to the main readme

- Makefile
- tests/pega-web-ready-release-testcases_jdk17_version.yaml
- tests/pega-web-ready-release-testcases_jdk21_version.yaml
Web ready image built on tomcat 10 & jdk 21
> US-655261 build web ready on tomcat10, jdk21 image

- README.md
- scripts/docker-entrypoint.sh
- tests/pega-web-ready-testcases.yaml
- tests/test-artifacts/web.xml
This is a proposed solution for US-613462 and https://github.com/pegasystems/pega-helm-charts/issues/577 which allows a user of the pega Helm chart to define an env variable WEB_XML_SNIPPET which will be inserted into the web.xml just before the tag. This allows users to:
Add an additional servlet
Add a security constraint
Add JMS resources
Without the snippet feature, the user needs to either embed an entire 1600+ line web.xml into their values file, or put a replacement web.xml into the config/deploy folder (which either means using local charts instead of hosting in a repository, or having to repackage every chart release with the customization).
This feature also pairs with the existing functionality we have for specifying a CONTEXT_XML_SNIPPET.
> Add contents of WEB_XML_SNIPPET to web.xml

- .grype.yaml
- tomcat-webapps/ROOT/index.jsp
Only return 302 for requests to index.jsp, 404s for other requests.
Returning 302 for everything appears to interfere with external authentication because of browser-initiated requests for favicon.ico.
> Only return 302 for requests to index.jsp, 404s for other requests.
